### ISSUE TITLE
Transition between pages

### ISSUE THREAD

**Issue by Paul-Reed** [joedf/strapdown-topbar#1]
When navigating between pages, you can see momentarily - unstyled elements of the menu code, instead of the page remaining blank. I managed to grab a screenshot of what you actually see, before the selected page fully loads.

![transit](https://cloud.githubusercontent.com/assets/973580/10361850/c396c9f8-6da2-11e5-8329-155d6de6612a.jpg)

**Comment by Paul-Reed** [comment]
Oh I forgot to say; you've done a great job developing this menu bar. It looks great and adds a lot of value to the original Strapdown project. Thanks!

**Comment by joedf** [comment]
Thanks! :+1: 
And, yes good catch, actually. It's quite simple, I had forgotten about it, but just add `style="display:none;"` to the topbar tag. I have updated all examples.

By the way, don't forget to star this repo! ;)

**Comment by Paul-Reed** [comment]
Thanks, that's much better!
