### ISSUE TITLE
TOC not collapsing

### ISSUE THREAD

**Issue by Paul-Reed** [joedf/strapdown-topbar#2]
Noticed that the TOC menu does not collapse once a selection has been made, and the only way to collapse it is to either click away from the menu, or select another menu item.
This is more of a problem when using a mobile device, because if you tap elsewhere on the screen, the TOC menu collapses, but the main menu remains expanded.
![toc](https://cloud.githubusercontent.com/assets/973580/10402196/c7ec6494-6ebb-11e5-92ea-2457fb00ae40.png)

**Comment by joedf** [comment]
Yes, agreed. I'm also thinking of having a hierarchy for the TOC. I'll have it disappear in on mobile, and leave the desktop behaviour as is. I'll do this when I get home, and if time permits, add a test version for hierarchy.

**Comment by joedf** [comment]
Ok, I got it. Im having an unexpected issue. I should be able to have it up soon.

**Comment by Paul-Reed** [comment]
Great news,  however there's no rush. The menu bar works fine at the moment, and these small tweaks are just enhancements.
